// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage_MessageType int32

const (
	AgentMessage_RESPONSE     AgentMessage_MessageType = 0 // Regular response or intermediate question
	AgentMessage_FINAL_RESULT AgentMessage_MessageType = 1 // Final result; stream will close after this
	AgentMessage_ERROR        AgentMessage_MessageType = 2 // Error occurred
)

// Enum value maps for AgentMessage_MessageType.
var (
	AgentMessage_MessageType_name = map[int32]string{
		0: "RESPONSE",
		1: "FINAL_RESULT",
		2: "ERROR",
	}
	AgentMessage_MessageType_value = map[string]int32{
		"RESPONSE":     0,
		"FINAL_RESULT": 1,
		"ERROR":        2,
	}
)

func (x AgentMessage_MessageType) Enum() *AgentMessage_MessageType {
	p := new(AgentMessage_MessageType)
	*p = x
	return p
}

func (x AgentMessage_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentMessage_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (AgentMessage_MessageType) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x AgentMessage_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentMessage_MessageType.Descriptor instead.
func (AgentMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1, 0}
}

// ClientMessage: Message sent FROM client/user TO agent
type ClientMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                 // Target user whose context/data is relevant
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                                                             // User message or response to agent question
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                        // Optional session ID for context tracking
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., locale, channel, tenant
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClientMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ClientMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// AgentMessage: Message sent FROM agent TO client/user
type AgentMessage struct {
	state     protoimpl.MessageState   `protogen:"open.v1"`
	Type      AgentMessage_MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=agent.AgentMessage_MessageType" json:"type,omitempty"`
	Content   string                   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	SessionId string                   `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Optional: structured data (e.g., calendar events, recommendations)
	Data          map[string]string `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentMessage) GetType() AgentMessage_MessageType {
	if x != nil {
		return x.Type
	}
	return AgentMessage_RESPONSE
}

func (x *AgentMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AgentMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentMessage) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAgentStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // State scoped to a specific user/session
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Optional session scope
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStateRequest) Reset() {
	*x = GetAgentStateRequest{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStateRequest) ProtoMessage() {}

func (x *GetAgentStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStateRequest.ProtoReflect.Descriptor instead.
func (*GetAgentStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GetAgentStateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAgentStateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetAgentStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStateResponse) Reset() {
	*x = GetAgentStateResponse{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStateResponse) ProtoMessage() {}

func (x *GetAgentStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStateResponse.ProtoReflect.Descriptor instead.
func (*GetAgentStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *GetAgentStateResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *GetAgentStateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAgentStateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x05agent\"\xde\x01\n" +
	"\rClientMessage\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12>\n" +
	"\bmetadata\x18\x04 \x03(\v2\".agent.ClientMessage.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x02\n" +
	"\fAgentMessage\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.agent.AgentMessage.MessageTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x121\n" +
	"\x04data\x18\x04 \x03(\v2\x1d.agent.AgentMessage.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\vMessageType\x12\f\n" +
	"\bRESPONSE\x10\x00\x12\x10\n" +
	"\fFINAL_RESULT\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\"N\n" +
	"\x14GetAgentStateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"_\n" +
	"\x15GetAgentStateResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x9b\x01\n" +
	"\fAgentService\x12?\n" +
	"\x0eProcessMessage\x12\x14.agent.ClientMessage\x1a\x13.agent.AgentMessage(\x010\x01\x12J\n" +
	"\rGetAgentState\x12\x1b.agent.GetAgentStateRequest\x1a\x1c.agent.GetAgentStateResponseB&H\x03Z\"github.com/waydxd/Orbit-Orbi/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_agent_proto_goTypes = []any{
	(AgentMessage_MessageType)(0), // 0: agent.AgentMessage.MessageType
	(*ClientMessage)(nil),         // 1: agent.ClientMessage
	(*AgentMessage)(nil),          // 2: agent.AgentMessage
	(*GetAgentStateRequest)(nil),  // 3: agent.GetAgentStateRequest
	(*GetAgentStateResponse)(nil), // 4: agent.GetAgentStateResponse
	nil,                           // 5: agent.ClientMessage.MetadataEntry
	nil,                           // 6: agent.AgentMessage.DataEntry
}
var file_proto_agent_proto_depIdxs = []int32{
	5, // 0: agent.ClientMessage.metadata:type_name -> agent.ClientMessage.MetadataEntry
	0, // 1: agent.AgentMessage.type:type_name -> agent.AgentMessage.MessageType
	6, // 2: agent.AgentMessage.data:type_name -> agent.AgentMessage.DataEntry
	1, // 3: agent.AgentService.ProcessMessage:input_type -> agent.ClientMessage
	3, // 4: agent.AgentService.GetAgentState:input_type -> agent.GetAgentStateRequest
	2, // 5: agent.AgentService.ProcessMessage:output_type -> agent.AgentMessage
	4, // 6: agent.AgentService.GetAgentState:output_type -> agent.GetAgentStateResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
