// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/calendar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalendarQuery_QueryType int32

const (
	CalendarQuery_GET_EVENTS          CalendarQuery_QueryType = 0 // Get events in a time range
	CalendarQuery_GET_AVAILABILITY    CalendarQuery_QueryType = 1 // Check if user is available at a specific time
	CalendarQuery_GET_AVAILABLE_SLOTS CalendarQuery_QueryType = 2 // Find available time slots
	CalendarQuery_CREATE_EVENT        CalendarQuery_QueryType = 3 // Create a new event
	CalendarQuery_UPDATE_EVENT        CalendarQuery_QueryType = 4 // Update an existing event
	CalendarQuery_DELETE_EVENT        CalendarQuery_QueryType = 5 // Delete an event
	CalendarQuery_QUERY_EVENTS        CalendarQuery_QueryType = 6 // Free-form query (search)
)

// Enum value maps for CalendarQuery_QueryType.
var (
	CalendarQuery_QueryType_name = map[int32]string{
		0: "GET_EVENTS",
		1: "GET_AVAILABILITY",
		2: "GET_AVAILABLE_SLOTS",
		3: "CREATE_EVENT",
		4: "UPDATE_EVENT",
		5: "DELETE_EVENT",
		6: "QUERY_EVENTS",
	}
	CalendarQuery_QueryType_value = map[string]int32{
		"GET_EVENTS":          0,
		"GET_AVAILABILITY":    1,
		"GET_AVAILABLE_SLOTS": 2,
		"CREATE_EVENT":        3,
		"UPDATE_EVENT":        4,
		"DELETE_EVENT":        5,
		"QUERY_EVENTS":        6,
	}
)

func (x CalendarQuery_QueryType) Enum() *CalendarQuery_QueryType {
	p := new(CalendarQuery_QueryType)
	*p = x
	return p
}

func (x CalendarQuery_QueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CalendarQuery_QueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_calendar_proto_enumTypes[0].Descriptor()
}

func (CalendarQuery_QueryType) Type() protoreflect.EnumType {
	return &file_proto_calendar_proto_enumTypes[0]
}

func (x CalendarQuery_QueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CalendarQuery_QueryType.Descriptor instead.
func (CalendarQuery_QueryType) EnumDescriptor() ([]byte, []int) {
	return file_proto_calendar_proto_rawDescGZIP(), []int{1, 0}
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	StartTime     int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Unix timestamp (seconds)
	EndTime       int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // Unix timestamp (seconds)
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Attendees     []string               `protobuf:"bytes,8,rep,name=attendees,proto3" json:"attendees,omitempty"`
	Recurrence    string                 `protobuf:"bytes,9,opt,name=recurrence,proto3" json:"recurrence,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"` // e.g., "confirmed", "tentative", "cancelled"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_calendar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_calendar_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Event) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Event) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Event) GetAttendees() []string {
	if x != nil {
		return x.Attendees
	}
	return nil
}

func (x *Event) GetRecurrence() string {
	if x != nil {
		return x.Recurrence
	}
	return ""
}

func (x *Event) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// CalendarQuery: Message sent FROM agent TO calendar
type CalendarQuery struct {
	state  protoimpl.MessageState  `protogen:"open.v1"`
	Type   CalendarQuery_QueryType `protobuf:"varint,1,opt,name=type,proto3,enum=calendar.CalendarQuery_QueryType" json:"type,omitempty"`
	UserId string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Depending on type, use relevant fields:
	StartTime int64 `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // For GET_EVENTS, GET_AVAILABILITY, GET_AVAILABLE_SLOTS
	EndTime   int64 `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Duration  int64 `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"` // For GET_AVAILABLE_SLOTS (in seconds)
	// For CREATE_EVENT, UPDATE_EVENT, DELETE_EVENT
	Event *Event `protobuf:"bytes,6,opt,name=event,proto3" json:"event,omitempty"`
	// For QUERY_EVENTS
	Query         string   `protobuf:"bytes,7,opt,name=query,proto3" json:"query,omitempty"`
	Tags          []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalendarQuery) Reset() {
	*x = CalendarQuery{}
	mi := &file_proto_calendar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarQuery) ProtoMessage() {}

func (x *CalendarQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarQuery.ProtoReflect.Descriptor instead.
func (*CalendarQuery) Descriptor() ([]byte, []int) {
	return file_proto_calendar_proto_rawDescGZIP(), []int{1}
}

func (x *CalendarQuery) GetType() CalendarQuery_QueryType {
	if x != nil {
		return x.Type
	}
	return CalendarQuery_GET_EVENTS
}

func (x *CalendarQuery) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CalendarQuery) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CalendarQuery) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *CalendarQuery) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CalendarQuery) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *CalendarQuery) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CalendarQuery) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// CalendarQueryResponse: Message sent FROM calendar TO agent
type CalendarQueryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Events             []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	AvailableSlots     []*TimeSlot            `protobuf:"bytes,2,rep,name=available_slots,json=availableSlots,proto3" json:"available_slots,omitempty"`
	AvailabilityStatus *AvailabilityStatus    `protobuf:"bytes,3,opt,name=availability_status,json=availabilityStatus,proto3" json:"availability_status,omitempty"`
	Success            bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Message            string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CalendarQueryResponse) Reset() {
	*x = CalendarQueryResponse{}
	mi := &file_proto_calendar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarQueryResponse) ProtoMessage() {}

func (x *CalendarQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarQueryResponse.ProtoReflect.Descriptor instead.
func (*CalendarQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_proto_rawDescGZIP(), []int{2}
}

func (x *CalendarQueryResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *CalendarQueryResponse) GetAvailableSlots() []*TimeSlot {
	if x != nil {
		return x.AvailableSlots
	}
	return nil
}

func (x *CalendarQueryResponse) GetAvailabilityStatus() *AvailabilityStatus {
	if x != nil {
		return x.AvailabilityStatus
	}
	return nil
}

func (x *CalendarQueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CalendarQueryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TimeSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSlot) Reset() {
	*x = TimeSlot{}
	mi := &file_proto_calendar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlot) ProtoMessage() {}

func (x *TimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlot.ProtoReflect.Descriptor instead.
func (*TimeSlot) Descriptor() ([]byte, []int) {
	return file_proto_calendar_proto_rawDescGZIP(), []int{3}
}

func (x *TimeSlot) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TimeSlot) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type AvailabilityStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Available         bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Reason            string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ConflictingEvents []*Event               `protobuf:"bytes,3,rep,name=conflicting_events,json=conflictingEvents,proto3" json:"conflicting_events,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AvailabilityStatus) Reset() {
	*x = AvailabilityStatus{}
	mi := &file_proto_calendar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityStatus) ProtoMessage() {}

func (x *AvailabilityStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityStatus.ProtoReflect.Descriptor instead.
func (*AvailabilityStatus) Descriptor() ([]byte, []int) {
	return file_proto_calendar_proto_rawDescGZIP(), []int{4}
}

func (x *AvailabilityStatus) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *AvailabilityStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AvailabilityStatus) GetConflictingEvents() []*Event {
	if x != nil {
		return x.ConflictingEvents
	}
	return nil
}

var File_proto_calendar_proto protoreflect.FileDescriptor

const file_proto_calendar_proto_rawDesc = "" +
	"\n" +
	"\x14proto/calendar.proto\x12\bcalendar\"\x94\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1c\n" +
	"\tattendees\x18\b \x03(\tR\tattendees\x12\x1e\n" +
	"\n" +
	"recurrence\x18\t \x01(\tR\n" +
	"recurrence\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\"\x9b\x03\n" +
	"\rCalendarQuery\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.calendar.CalendarQuery.QueryTypeR\x04type\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x03R\bduration\x12%\n" +
	"\x05event\x18\x06 \x01(\v2\x0f.calendar.EventR\x05event\x12\x14\n" +
	"\x05query\x18\a \x01(\tR\x05query\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\"\x92\x01\n" +
	"\tQueryType\x12\x0e\n" +
	"\n" +
	"GET_EVENTS\x10\x00\x12\x14\n" +
	"\x10GET_AVAILABILITY\x10\x01\x12\x17\n" +
	"\x13GET_AVAILABLE_SLOTS\x10\x02\x12\x10\n" +
	"\fCREATE_EVENT\x10\x03\x12\x10\n" +
	"\fUPDATE_EVENT\x10\x04\x12\x10\n" +
	"\fDELETE_EVENT\x10\x05\x12\x10\n" +
	"\fQUERY_EVENTS\x10\x06\"\x80\x02\n" +
	"\x15CalendarQueryResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events\x12;\n" +
	"\x0favailable_slots\x18\x02 \x03(\v2\x12.calendar.TimeSlotR\x0eavailableSlots\x12M\n" +
	"\x13availability_status\x18\x03 \x01(\v2\x1c.calendar.AvailabilityStatusR\x12availabilityStatus\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"D\n" +
	"\bTimeSlot\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\"\x8a\x01\n" +
	"\x12AvailabilityStatus\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12>\n" +
	"\x12conflicting_events\x18\x03 \x03(\v2\x0f.calendar.EventR\x11conflictingEvents2i\n" +
	"\x14CalendarQueryService\x12Q\n" +
	"\x11QueryCalendarData\x12\x17.calendar.CalendarQuery\x1a\x1f.calendar.CalendarQueryResponse(\x010\x01B&H\x03Z\"github.com/waydxd/Orbit-Orbi/protob\x06proto3"

var (
	file_proto_calendar_proto_rawDescOnce sync.Once
	file_proto_calendar_proto_rawDescData []byte
)

func file_proto_calendar_proto_rawDescGZIP() []byte {
	file_proto_calendar_proto_rawDescOnce.Do(func() {
		file_proto_calendar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calendar_proto_rawDesc), len(file_proto_calendar_proto_rawDesc)))
	})
	return file_proto_calendar_proto_rawDescData
}

var file_proto_calendar_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_calendar_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_calendar_proto_goTypes = []any{
	(CalendarQuery_QueryType)(0),  // 0: calendar.CalendarQuery.QueryType
	(*Event)(nil),                 // 1: calendar.Event
	(*CalendarQuery)(nil),         // 2: calendar.CalendarQuery
	(*CalendarQueryResponse)(nil), // 3: calendar.CalendarQueryResponse
	(*TimeSlot)(nil),              // 4: calendar.TimeSlot
	(*AvailabilityStatus)(nil),    // 5: calendar.AvailabilityStatus
}
var file_proto_calendar_proto_depIdxs = []int32{
	0, // 0: calendar.CalendarQuery.type:type_name -> calendar.CalendarQuery.QueryType
	1, // 1: calendar.CalendarQuery.event:type_name -> calendar.Event
	1, // 2: calendar.CalendarQueryResponse.events:type_name -> calendar.Event
	4, // 3: calendar.CalendarQueryResponse.available_slots:type_name -> calendar.TimeSlot
	5, // 4: calendar.CalendarQueryResponse.availability_status:type_name -> calendar.AvailabilityStatus
	1, // 5: calendar.AvailabilityStatus.conflicting_events:type_name -> calendar.Event
	2, // 6: calendar.CalendarQueryService.QueryCalendarData:input_type -> calendar.CalendarQuery
	3, // 7: calendar.CalendarQueryService.QueryCalendarData:output_type -> calendar.CalendarQueryResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_calendar_proto_init() }
func file_proto_calendar_proto_init() {
	if File_proto_calendar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calendar_proto_rawDesc), len(file_proto_calendar_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calendar_proto_goTypes,
		DependencyIndexes: file_proto_calendar_proto_depIdxs,
		EnumInfos:         file_proto_calendar_proto_enumTypes,
		MessageInfos:      file_proto_calendar_proto_msgTypes,
	}.Build()
	File_proto_calendar_proto = out.File
	file_proto_calendar_proto_goTypes = nil
	file_proto_calendar_proto_depIdxs = nil
}
