// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/calendar.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CalendarQueryService_QueryCalendarData_FullMethodName = "/calendar.CalendarQueryService/QueryCalendarData"
)

// CalendarQueryServiceClient is the client API for CalendarQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CalendarQueryService: Bidirectional streaming for Agent <-> Calendar communication.
// Implemented by Calendar. Consumed by Agent.
// NOTE: Calendar exposes NO other endpoints. It only connects to Agent and responds to queries.
type CalendarQueryServiceClient interface {
	// QueryCalendarData: Bidirectional stream where agent sends queries and calendar responds with data.
	QueryCalendarData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CalendarQuery, CalendarQueryResponse], error)
}

type calendarQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalendarQueryServiceClient(cc grpc.ClientConnInterface) CalendarQueryServiceClient {
	return &calendarQueryServiceClient{cc}
}

func (c *calendarQueryServiceClient) QueryCalendarData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CalendarQuery, CalendarQueryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CalendarQueryService_ServiceDesc.Streams[0], CalendarQueryService_QueryCalendarData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CalendarQuery, CalendarQueryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalendarQueryService_QueryCalendarDataClient = grpc.BidiStreamingClient[CalendarQuery, CalendarQueryResponse]

// CalendarQueryServiceServer is the server API for CalendarQueryService service.
// All implementations must embed UnimplementedCalendarQueryServiceServer
// for forward compatibility.
//
// CalendarQueryService: Bidirectional streaming for Agent <-> Calendar communication.
// Implemented by Calendar. Consumed by Agent.
// NOTE: Calendar exposes NO other endpoints. It only connects to Agent and responds to queries.
type CalendarQueryServiceServer interface {
	// QueryCalendarData: Bidirectional stream where agent sends queries and calendar responds with data.
	QueryCalendarData(grpc.BidiStreamingServer[CalendarQuery, CalendarQueryResponse]) error
	mustEmbedUnimplementedCalendarQueryServiceServer()
}

// UnimplementedCalendarQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCalendarQueryServiceServer struct{}

func (UnimplementedCalendarQueryServiceServer) QueryCalendarData(grpc.BidiStreamingServer[CalendarQuery, CalendarQueryResponse]) error {
	return status.Errorf(codes.Unimplemented, "method QueryCalendarData not implemented")
}
func (UnimplementedCalendarQueryServiceServer) mustEmbedUnimplementedCalendarQueryServiceServer() {}
func (UnimplementedCalendarQueryServiceServer) testEmbeddedByValue()                              {}

// UnsafeCalendarQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalendarQueryServiceServer will
// result in compilation errors.
type UnsafeCalendarQueryServiceServer interface {
	mustEmbedUnimplementedCalendarQueryServiceServer()
}

func RegisterCalendarQueryServiceServer(s grpc.ServiceRegistrar, srv CalendarQueryServiceServer) {
	// If the following call pancis, it indicates UnimplementedCalendarQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CalendarQueryService_ServiceDesc, srv)
}

func _CalendarQueryService_QueryCalendarData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalendarQueryServiceServer).QueryCalendarData(&grpc.GenericServerStream[CalendarQuery, CalendarQueryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalendarQueryService_QueryCalendarDataServer = grpc.BidiStreamingServer[CalendarQuery, CalendarQueryResponse]

// CalendarQueryService_ServiceDesc is the grpc.ServiceDesc for CalendarQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalendarQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calendar.CalendarQueryService",
	HandlerType: (*CalendarQueryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryCalendarData",
			Handler:       _CalendarQueryService_QueryCalendarData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/calendar.proto",
}
